zig test ./src/mustache.zig --test-filter  "Inline" 
zig test ./src/mustache.zig --test-filter  "Multiline"
zig test ./src/mustache.zig --test-filter  "Standalone"
zig test ./src/mustache.zig --test-filter  "Indented Standalone"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Multiline Standalone"
zig test ./src/mustache.zig --test-filter  "Indented Multiline Standalone"
zig test ./src/mustache.zig --test-filter  "Indented Inline"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Pair Behavior"
zig test ./src/mustache.zig --test-filter  "Special Characters"
zig test ./src/mustache.zig --test-filter  "Sections"
zig test ./src/mustache.zig --test-filter  "Inverted Sections"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Outlying Whitespace (Inline)"
zig test ./src/mustache.zig --test-filter  "Standalone Tag"
zig test ./src/mustache.zig --test-filter  "Indented Standalone Tag"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Pair with Padding"
zig test ./src/mustache.zig --test-filter  "No Interpolation"
zig test ./src/mustache.zig --test-filter  "Basic Interpolation"
zig test ./src/mustache.zig --test-filter  "HTML Escaping"
zig test ./src/mustache.zig --test-filter  "Triple Mustache"
zig test ./src/mustache.zig --test-filter  "Ampersand"
zig test ./src/mustache.zig --test-filter  "Interpolation - Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Triple Mustache - Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Ampersand - Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Interpolation - Standalone"
zig test ./src/mustache.zig --test-filter  "Triple Mustache - Standalone"
zig test ./src/mustache.zig --test-filter  "Ampersand - Standalone"
zig test ./src/mustache.zig --test-filter  "Interpolation With Padding"
zig test ./src/mustache.zig --test-filter  "Triple Mustache With Padding"
zig test ./src/mustache.zig --test-filter  "Ampersand With Padding"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Internal Whitespace"
zig test ./src/mustache.zig --test-filter  "Indented Inline Sections"
zig test ./src/mustache.zig --test-filter  "Standalone Lines"
zig test ./src/mustache.zig --test-filter  "Indented Standalone Lines"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Padding"
zig test ./src/mustache.zig --test-filter  "Deeply Nested Contexts"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Internal Whitespace"
zig test ./src/mustache.zig --test-filter  "Indented Inline Sections"
zig test ./src/mustache.zig --test-filter  "Standalone Lines"
zig test ./src/mustache.zig --test-filter  "Indented Standalone Lines"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Standalone Indented Lines"
zig test ./src/mustache.zig --test-filter  "Padding"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Inline Indentation"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Standalone Indentation"
zig test ./src/mustache.zig --test-filter  "Padding"
zig test ./src/mustache.zig --test-filter  "Sections"
zig test ./src/mustache.zig --test-filter  "Nested Sections"
zig test ./src/mustache.zig --test-filter  "Basic DOM test"
zig test ./src/mustache.zig --test-filter  "Basic DOM File test"
zig test ./src/mustache.zig --test-filter  "Large DOM File test"
zig test ./src/mustache.zig --test-filter  "parseText API"
zig test ./src/mustache.zig --test-filter  "parseComptime API"
zig test ./src/mustache.zig --test-filter  "parseFile API"
zig test ./src/mustache.zig --test-filter  "FileReader.Slices"
zig test ./src/mustache.zig --test-filter  "Basic parse"
zig test ./src/mustache.zig --test-filter  "Scan standAlone tags"
zig test ./src/mustache.zig --test-filter  "Scan delimiters Tags"
zig test ./src/mustache.zig --test-filter  "Parse - UnexpectedCloseSection "
zig test ./src/mustache.zig --test-filter  "Parse - Invalid delimiter"
zig test ./src/mustache.zig --test-filter  "Parse - Invalid identifier"
zig test ./src/mustache.zig --test-filter  "Parse - ClosingTagMismatch "
zig test ./src/mustache.zig --test-filter  "ref and free"
zig test ./src/mustache.zig --test-filter  "basic tests"
zig test ./src/mustache.zig --test-filter  "custom tags"
zig test ./src/mustache.zig --test-filter  "EOF"
zig test ./src/mustache.zig --test-filter  "EOF custom tags"
zig test ./src/mustache.zig --test-filter  "bookmarks"
zig test ./src/mustache.zig --test-filter  "Line breaks"
zig test ./src/mustache.zig --test-filter  "Line breaks \\r\\n"
zig test ./src/mustache.zig --test-filter  "Multiple line breaks"
zig test ./src/mustache.zig --test-filter  "Multiple line breaks \\r\\n"
zig test ./src/mustache.zig --test-filter  "Whitespace text trimming"
zig test ./src/mustache.zig --test-filter  "Whitespace text trimming \\r\\n"
zig test ./src/mustache.zig --test-filter  "Tabs text trimming"
zig test ./src/mustache.zig --test-filter  "Whitespace left trimming"
zig test ./src/mustache.zig --test-filter  "Whitespace left trimming \\r\\n"
zig test ./src/mustache.zig --test-filter  "Tabs left trimming"
zig test ./src/mustache.zig --test-filter  "Whitespace right trimming"
zig test ./src/mustache.zig --test-filter  "Whitespace right trimming \\r\\n"
zig test ./src/mustache.zig --test-filter  "Tabs right trimming"
zig test ./src/mustache.zig --test-filter  "Single line break"
zig test ./src/mustache.zig --test-filter  "Single line break \\r\\n"
zig test ./src/mustache.zig --test-filter  "No trimming"
zig test ./src/mustache.zig --test-filter  "No trimming, no whitespace"
zig test ./src/mustache.zig --test-filter  "No trimming, no whitespace \\r\\n"
zig test ./src/mustache.zig --test-filter  "No trimming \\r\\n"
zig test ./src/mustache.zig --test-filter  "No whitespace"
zig test ./src/mustache.zig --test-filter  "Trimming left only"
zig test ./src/mustache.zig --test-filter  "Trimming left only \\r\\n"
zig test ./src/mustache.zig --test-filter  "Trimming right only"
zig test ./src/mustache.zig --test-filter  "Trimming right only \\r\\n"
zig test ./src/mustache.zig --test-filter  "Only whitespace"
zig test ./src/mustache.zig --test-filter  "Only tabs"
zig test ./src/mustache.zig --test-filter  "Needs derref"
zig test ./src/mustache.zig --test-filter  "Ref values"
zig test ./src/mustache.zig --test-filter  "Const ref values"
zig test ./src/mustache.zig --test-filter  "comptime int"
zig test ./src/mustache.zig --test-filter  "comptime floats"
zig test ./src/mustache.zig --test-filter  "enum literal "
zig test ./src/mustache.zig --test-filter  "enum"
zig test ./src/mustache.zig --test-filter  "strings"
zig test ./src/mustache.zig --test-filter  "slices"
zig test ./src/mustache.zig --test-filter  "slices items"
zig test ./src/mustache.zig --test-filter  "array items"
zig test ./src/mustache.zig --test-filter  "tuple items"
zig test ./src/mustache.zig --test-filter  "optionals"
zig test ./src/mustache.zig --test-filter  "optional pointers"
zig test ./src/mustache.zig --test-filter  "ref optionals"
zig test ./src/mustache.zig --test-filter  "zero size"
zig test ./src/mustache.zig --test-filter  "nested"
zig test ./src/mustache.zig --test-filter  "Indent/Unindent"
zig test ./src/mustache.zig --test-filter  "Map single tuple"
zig test ./src/mustache.zig --test-filter  "Map empty tuple"
zig test ./src/mustache.zig --test-filter  "Map void"
zig test ./src/mustache.zig --test-filter  "Map multiple tuple"
zig test ./src/mustache.zig --test-filter  "Map array"
zig test ./src/mustache.zig --test-filter  "Map ref array"
zig test ./src/mustache.zig --test-filter  "Map slice"
zig test ./src/mustache.zig --test-filter  "Map hashmap"
zig test ./src/mustache.zig --test-filter  "No Interpolation"
zig test ./src/mustache.zig --test-filter  "Basic Interpolation"
zig test ./src/mustache.zig --test-filter  "HTML Escaping"
zig test ./src/mustache.zig --test-filter  "Triple Mustache"
zig test ./src/mustache.zig --test-filter  "Ampersand"
zig test ./src/mustache.zig --test-filter  "Basic Integer Interpolation"
zig test ./src/mustache.zig --test-filter  "Triple Mustache Integer Interpolation"
zig test ./src/mustache.zig --test-filter  "Ampersand Integer Interpolation"
zig test ./src/mustache.zig --test-filter  "Basic Decimal Interpolation"
zig test ./src/mustache.zig --test-filter  "Triple Mustache Decimal Interpolation"
zig test ./src/mustache.zig --test-filter  "Ampersand Decimal Interpolation"
zig test ./src/mustache.zig --test-filter  "Basic Null Interpolation"
zig test ./src/mustache.zig --test-filter  "Triple Mustache Null Interpolation"
zig test ./src/mustache.zig --test-filter  "Ampersand Null Interpolation"
zig test ./src/mustache.zig --test-filter  "Basic Context Miss Interpolation"
zig test ./src/mustache.zig --test-filter  "Triple Mustache Context Miss Interpolation"
zig test ./src/mustache.zig --test-filter  "Ampersand Context Miss Interpolation"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Basic Interpolation"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Triple Mustache Interpolation"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Ampersand Interpolation"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Arbitrary Depth"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Broken Chains"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Broken Chain Resolution"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Initial Resolution"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Context Precedence"
zig test ./src/mustache.zig --test-filter  "Implicit Iterators - Basic Interpolation"
zig test ./src/mustache.zig --test-filter  "Implicit Iterators - HTML Escaping"
zig test ./src/mustache.zig --test-filter  "Implicit Iterators - Triple Mustache"
zig test ./src/mustache.zig --test-filter  "Implicit Iterators - Ampersand"
zig test ./src/mustache.zig --test-filter  "Implicit Iterators - Basic Integer Interpolation"
zig test ./src/mustache.zig --test-filter  "Interpolation - Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Triple Mustache - Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Ampersand - Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Interpolation - Standalone"
zig test ./src/mustache.zig --test-filter  "Triple Mustache - Standalone"
zig test ./src/mustache.zig --test-filter  "Ampersand - Standalone"
zig test ./src/mustache.zig --test-filter  "Interpolation With Padding"
zig test ./src/mustache.zig --test-filter  "Triple Mustache With Padding"
zig test ./src/mustache.zig --test-filter  "Ampersand With Padding"
zig test ./src/mustache.zig --test-filter  "Truthy"
zig test ./src/mustache.zig --test-filter  "Falsey"
zig test ./src/mustache.zig --test-filter  "Null is falsey"
zig test ./src/mustache.zig --test-filter  "Context"
zig test ./src/mustache.zig --test-filter  "Parent contexts"
zig test ./src/mustache.zig --test-filter  "Variable test"
zig test ./src/mustache.zig --test-filter  "List Contexts"
zig test ./src/mustache.zig --test-filter  "Deeply Nested Contexts"
zig test ./src/mustache.zig --test-filter  "List"
zig test ./src/mustache.zig --test-filter  "Empty List"
zig test ./src/mustache.zig --test-filter  "Doubled"
zig test ./src/mustache.zig --test-filter  "Nested (Truthy)"
zig test ./src/mustache.zig --test-filter  "Nested (Falsey)"
zig test ./src/mustache.zig --test-filter  "Context Misses"
zig test ./src/mustache.zig --test-filter  "Implicit Iterator - String"
zig test ./src/mustache.zig --test-filter  "Implicit Iterator - Integer"
zig test ./src/mustache.zig --test-filter  "Implicit Iterator - Decimal"
zig test ./src/mustache.zig --test-filter  "Implicit Iterator - Array"
zig test ./src/mustache.zig --test-filter  "Implicit Iterator - Mixed Array"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Truthy"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Falsey"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Broken Chains"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Internal Whitespace"
zig test ./src/mustache.zig --test-filter  "Indented Inline Sections"
zig test ./src/mustache.zig --test-filter  "Standalone Lines"
zig test ./src/mustache.zig --test-filter  "Indented Standalone Lines"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Padding"
zig test ./src/mustache.zig --test-filter  "Falsey"
zig test ./src/mustache.zig --test-filter  "Truthy"
zig test ./src/mustache.zig --test-filter  "Null is falsey"
zig test ./src/mustache.zig --test-filter  "Context"
zig test ./src/mustache.zig --test-filter  "List"
zig test ./src/mustache.zig --test-filter  "Empty List"
zig test ./src/mustache.zig --test-filter  "Doubled"
zig test ./src/mustache.zig --test-filter  "Nested (Falsey)"
zig test ./src/mustache.zig --test-filter  "Nested (Truthy)"
zig test ./src/mustache.zig --test-filter  "Context Misses"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Truthy"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Falsey"
zig test ./src/mustache.zig --test-filter  "Dotted Names - Broken Chains"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Internal Whitespace"
zig test ./src/mustache.zig --test-filter  "Indented Inline Sections"
zig test ./src/mustache.zig --test-filter  "Standalone Lines"
zig test ./src/mustache.zig --test-filter  "Standalone Indented Lines"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Padding"
zig test ./src/mustache.zig --test-filter  "Pair Behavior"
zig test ./src/mustache.zig --test-filter  "Special Characters"
zig test ./src/mustache.zig --test-filter  "Sections"
zig test ./src/mustache.zig --test-filter  "Inverted Sections"
zig test ./src/mustache.zig --test-filter  "Partial Inheritence"
zig test ./src/mustache.zig --test-filter  "Post-Partial Behavior"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Outlying Whitespace (Inline)"
zig test ./src/mustache.zig --test-filter  "Indented Standalone Tag"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Pair with Padding"
zig test ./src/mustache.zig --test-filter  "Interpolation"
zig test ./src/mustache.zig --test-filter  "Interpolation - Expansion"
zig test ./src/mustache.zig --test-filter  "Interpolation - Alternate Delimiters"
zig test ./src/mustache.zig --test-filter  "Interpolation - Multiple Calls"
zig test ./src/mustache.zig --test-filter  "Escaping"
zig test ./src/mustache.zig --test-filter  "Section"
zig test ./src/mustache.zig --test-filter  "Section - Expansion"
zig test ./src/mustache.zig --test-filter  "Section - Alternate Delimiters"
zig test ./src/mustache.zig --test-filter  "Section - Multiple Calls"
zig test ./src/mustache.zig --test-filter  "Inverted Section"
zig test ./src/mustache.zig --test-filter  "Basic Behavior"
zig test ./src/mustache.zig --test-filter  "Failed Lookup"
zig test ./src/mustache.zig --test-filter  "Context"
zig test ./src/mustache.zig --test-filter  "Recursion"
zig test ./src/mustache.zig --test-filter  "Surrounding Whitespace"
zig test ./src/mustache.zig --test-filter  "Inline Indentation"
zig test ./src/mustache.zig --test-filter  "Standalone Line Endings"
zig test ./src/mustache.zig --test-filter  "Standalone Without Previous Line"
zig test ./src/mustache.zig --test-filter  "Standalone Without Newline"
zig test ./src/mustache.zig --test-filter  "Standalone indentation"
zig test ./src/mustache.zig --test-filter  "Padding Whitespace"
zig test ./src/mustache.zig --test-filter  "Emoji"
zig test ./src/mustache.zig --test-filter  "Emoji as delimiter"
zig test ./src/mustache.zig --test-filter  "UTF-8"
zig test ./src/mustache.zig --test-filter  "Context stack resolution"
zig test ./src/mustache.zig --test-filter  "Lambda - lower"
zig test ./src/mustache.zig --test-filter  "Lambda - nested"
zig test ./src/mustache.zig --test-filter  "Lambda - Pointer and Value"
zig test ./src/mustache.zig --test-filter  "Lambda - Zero size"
zig test ./src/mustache.zig --test-filter  "Lambda - processing"
zig test ./src/mustache.zig --test-filter  "Section Line breaks"
zig test ./src/mustache.zig --test-filter  "Nested partials with indentation"
zig test ./src/mustache.zig --test-filter  "render API"
zig test ./src/mustache.zig --test-filter  "allocRender API"
zig test ./src/mustache.zig --test-filter  "allocRenderZ API"
zig test ./src/mustache.zig --test-filter  "bufRender API"
zig test ./src/mustache.zig --test-filter  "bufRenderZ API"
zig test ./src/mustache.zig --test-filter  "bufRender error API"
zig test ./src/mustache.zig --test-filter  "bufRenderZ error API"
zig test ./src/mustache.zig --test-filter  "renderText API"
zig test ./src/mustache.zig --test-filter  "allocRenderText API"
zig test ./src/mustache.zig --test-filter  "allocRenderTextZ API"
zig test ./src/mustache.zig --test-filter  "renderFile API"
zig test ./src/mustache.zig --test-filter  "allocRenderFile API"
zig test ./src/mustache.zig --test-filter  "allocRenderFileZ API"
zig test ./src/mustache.zig --test-filter  "Escape"
zig test ./src/mustache.zig --test-filter  "Escape and Indentation"
zig test ./src/mustache.zig --test-filter  "Indentation"
zig test ./src/mustache.zig --test-filter  "FFI context get"
zig test ./src/mustache.zig --test-filter  "FFI context get children"
zig test ./src/mustache.zig --test-filter  "FFI Write"
zig test ./src/mustache.zig --test-filter  "FFI Write children"
zig test ./src/mustache.zig --test-filter  "FFI Render"
zig test ./src/mustache.zig --test-filter  "FFI children render"
zig test ./src/mustache.zig --test-filter  "FFI Section render"
zig test ./src/mustache.zig --test-filter  "Write Int"
zig test ./src/mustache.zig --test-filter  "Write Float"
zig test ./src/mustache.zig --test-filter  "Write String"
zig test ./src/mustache.zig --test-filter  "Write Enum"
zig test ./src/mustache.zig --test-filter  "Write Bool"
zig test ./src/mustache.zig --test-filter  "Write Nullable"
zig test ./src/mustache.zig --test-filter  "Write Not found"
zig test ./src/mustache.zig --test-filter  "Lambda - staticLambda"
zig test ./src/mustache.zig --test-filter  "Lambda - selfLambda"
zig test ./src/mustache.zig --test-filter  "Lambda - selfConstPtrLambda"
zig test ./src/mustache.zig --test-filter  "Lambda - Write selfMutPtrLambda"
zig test ./src/mustache.zig --test-filter  "Lambda - error handling"
zig test ./src/mustache.zig --test-filter  "Lambda - Write invalid functions"
zig test ./src/mustache.zig --test-filter  "Navigation"
zig test ./src/mustache.zig --test-filter  "Navigation Pointers"
zig test ./src/mustache.zig --test-filter  "Navigation NotFound"
zig test ./src/mustache.zig --test-filter  "Iterator over slice"
zig test ./src/mustache.zig --test-filter  "Iterator over bool"
zig test ./src/mustache.zig --test-filter  "Iterator over null"
zig test ./src/mustache.zig --test-filter  "isOnErrorSet"
zig test ./src/mustache.zig --test-filter  "Comptime seek - self"
zig test ./src/mustache.zig --test-filter  "Comptime seek - dot"
zig test ./src/mustache.zig --test-filter  "Comptime seek - not found"
zig test ./src/mustache.zig --test-filter  "Comptime seek - found"
zig test ./src/mustache.zig --test-filter  "Comptime seek - self null"
zig test ./src/mustache.zig --test-filter  "Comptime seek - self dot"
zig test ./src/mustache.zig --test-filter  "Comptime seek - found nested"
zig test ./src/mustache.zig --test-filter  "Comptime seek - not found nested"
zig test ./src/mustache.zig --test-filter  "Comptime seek - null nested"
zig test ./src/mustache.zig --test-filter  "Comptime iter - self"
zig test ./src/mustache.zig --test-filter  "Comptime iter consumed - self"
zig test ./src/mustache.zig --test-filter  "Comptime iter - dot"
zig test ./src/mustache.zig --test-filter  "Comptime iter consumed - dot"
zig test ./src/mustache.zig --test-filter  "Comptime seek - not found"
zig test ./src/mustache.zig --test-filter  "Comptime iter - found"
zig test ./src/mustache.zig --test-filter  "Comptime iter consumed - found"
zig test ./src/mustache.zig --test-filter  "Comptime iter - found nested"
zig test ./src/mustache.zig --test-filter  "Comptime iter consumed - found nested"
zig test ./src/mustache.zig --test-filter  "Comptime iter - not found nested"
zig test ./src/mustache.zig --test-filter  "Comptime iter - slice"
zig test ./src/mustache.zig --test-filter  "Comptime iter - array"
zig test ./src/mustache.zig --test-filter  "Comptime iter - tuple"
zig test ./src/mustache.zig --test-filter  "Comptime iter - nested slice"
zig test ./src/mustache.zig --test-filter  "Comptime iter - nested array"
zig test ./src/mustache.zig --test-filter  "Comptime iter - nested tuple"
zig test ./src/mustache.zig --test-filter  "isLambdaInvoker"
zig test ./src/mustache.zig --test-filter  "isValidLambdaFunction"
zig test ./src/mustache.zig --test-filter  "LambdaInvoker"
zig test ./src/mustache.zig --test-filter  "Zero-sized LambdaInvoker"

