graph LR

    subgraph "context resolution"
        DataSource[Data source]
        JsonContext[Json object]
        ZigContext[Zig struct]
        FfiContext[FFI context]
        Context[Data context]

        DataSource-->|statically typed|ZigContext
        DataSource-->|dynamically typed|JsonContext
        DataSource-->|foreign function interface|FfiContext
        ZigContext-->|comptime reflection|Context
        JsonContext-->|runtime key-value|Context
        FfiContext-->|callbacks|Context    
    end

    subgraph "parser"
        TemplateSource[Template source]
        Parser[/"mustache.parseText(...)"/]
        ComptimeParser[/"mustache.parseComptime(...)"/]
        FileParser[/"mustache.parseFile(...)"/]
        StreamedParser[/"mustache.renderText*(...)"/]
        StreamedFileParser[/"mustache.renderFile*(...)"/]
        
        TemplateSource-->|runtime string| Parser
        TemplateSource-->|comptime string|ComptimeParser
        TemplateSource-->|file|FileParser
        TemplateSource-->|runtime string| StreamedParser
        TemplateSource-->|file|StreamedFileParser
    end

    subgraph "render"
        Elements[Streamed render]

        Render[Render]
        OutputStream[/"mustache.render*(...)"/]
        Buffer[/"mustache.bufRender*(...)"/]
        Allocation[/"mustache.allocRender*(...)"/]
        Template[Template]
        
        Parser & FileParser-->|loads|Template
        ComptimeParser-->|declares|Template
        StreamedParser & StreamedFileParser-->|streamed parser|Elements

        Context-->Render
        Render[Render engine]
        Template-->Render
        Elements-->Render

        Render-->|render to a writer|OutputStream
        Render-->|render to a pre-allocated buffer|Buffer
        Render-->|render allocating a new string|Allocation
    end